### ISSUE TITLE
Where is ./configure?

### ISSUE THREAD

**Issue by pub-dom** [aconchillo/guile-json#13]
I noticed there is no ./configure.  So I ran the following from within the project directory, which resulted in errors (Fedora 25):

$ autoconf
configure.ac:27: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:28: error: possibly undefined macro: AM_SILENT_RULES

$ autoreconf 
configure.ac:27: error: required file 'build-aux/install-sh' not found
configure.ac:27:   'automake --add-missing' can install 'install-sh'
configure.ac:27: error: required file 'build-aux/missing' not found
configure.ac:27:   'automake --add-missing' can install 'missing'
autoreconf: automake failed with exit status: 1

These resulted in generating the ./configure script, but that ran into further errors:

$ ./configure 
configure: error: cannot find install-sh, install.sh, or shtool in build-aux "."/build-aux

Please provide clear directions on how to generate a clean 'configure' script, and any system/package level dependencies if those need to be pre-installed on Fedora/Centos hosts.

Thank you.

**Comment by amirouche** [comment]
did you try `autoreconf -vif` ?

**Comment by pub-dom** [comment]
Yes, 'autoreconf -vif' worked!  

Thank you for the  command. I would appreciate if you could add this to the doc.  Feel free to close this issue.

**Comment by aconchillo** [comment]
Done.
