### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by christopherlam** [aconchillo/guile-json#14]
Hello,
Not a complaint about quality of code. This module is superb.
I am exploring plugging it into Gnucash reporting engine. But Gnucash uses GPLv2 or GPLv3.
I don't know if it is acceptable, or rude, to ask for this module to be GPLv2. I apologize in advance if that's the case. The relevant work is at https://github.com/Gnucash/gnucash/pull/316 to upgrade the old jqplot code to chartjs.

**Comment by aconchillo** [comment]
I believe I could release it with dual license GPL and LGPL. I will try to figure out how to do that.

**Comment by christopherlam** [comment]
Thank you, I think this would work!

**Comment by aconchillo** [comment]
I'm thinking to use this text for the dual license:

;; guile-json is free software; you can redistribute it and/or
;; modify it under the terms of the GNU General Public License or
;; the GNU Lesser General Public License as published by the Free
;; Software Foundation; either version 3 of the License, or (at your
;; option) any later version.
;;
;; guile-json is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
;; General Public License and the GNU Lesser General Public License
;; for more details.
;;
;; You should have received a copy of the GNU General Public License
;; and the GNU Lesser General Public License along with guile-json;
;; if not, write to the Free Software Foundation, Inc.,
;; 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

**Comment by aconchillo** [comment]
I just asked GNU Licensing lab. I'll let you know.

**Comment by aconchillo** [comment]
I just release guile-json 1.0.0 with dual GPLv3 and LGPL3 licenses.

**Comment by aconchillo** [comment]
Hi! Now that I'm looking back at licenses, I was wondering why LGPLv3 was not good for GnuCash? Isn't LGPL supposed to be compatible to GPL? And actually isn't GnuCash using Gtk which has an LGPL license?

Thanks!

**Comment by christopherlam** [comment]
I suspect gnucash doesn't include gtk directly but rather links to it.

**Comment by aconchillo** [comment]
I see. I just downloaded GnuCash and saw you include guile-json source code, that's why you needed GPL.
