### ISSUE TITLE
the closing curly brace won't come

### ISSUE THREAD

**Issue by humanitiesNerd** [aconchillo/guile-json#23]
I'm afraid I'm running into a new bug

Or I am misunderstanding something

I built guile-json from the master branch

I copied the ping server provided as an example from the Fiber library

Then I changed the server [code](https://gitlab.com/humanitiesNerd/guile-lsp/blob/master/lsp-server.scm) a bit and this is a relevant excerpt

```
(define (client-loop port addr store)
  (setvbuf port 'block 1024)
  ;; Disable Nagle's algorithm.  We buffer ourselves.
  (setsockopt port IPPROTO_TCP TCP_NODELAY 1)
  (let loop ()
    ;; TODO: Restrict read-line to 512 chars.
    (let ((line (read-line port)))
      (cond
       ((eof-object? line)
        (close-port port))
       (else
        ;; TODO this is where the server is gonna cook up its replies

	(put-string port "Content-Length: 121\r\n")
	(put-string port "\r\n")

	(scm->json
	  (list
	   (cons "jsonrpc" "2.0")
	   (cons "id" 1)
	   (cons "method" "textDocument/didOpen"))  port #:pretty #t )  
	
        (force-output port)
	
        (loop))))))

```

So i have a Guile process running this server

I open another Guile and at the REPL I dive down in a [client](https://gitlab.com/humanitiesNerd/guile-lsp/blob/master/lsp-client.scm) module and then I try to connect to such server and display its reply

I type:

```
scheme@(lsp-client)> (getaddrinfo "localhost" "11211")
$1 = (#(0 2 1 6 #(2 2130706433 11211) #f) #(0 2 2 17 #(2 2130706433 11211) #f) #(0 2 3 0 #(2 2130706433 11211) #f))
scheme@(lsp-client)> (car $1)
$2 = #(0 2 1 6 #(2 2130706433 11211) #f)
scheme@(lsp-client)> (connect-to-server $2)
$3 = #<input-output: socket 13>
scheme@(lsp-client)> 
scheme@(lsp-client)> (put-string $3 "Hi !")
scheme@(lsp-client)> (put-char $3 #\newline)
scheme@(lsp-client)> (force-output $3)
```

so I sent a request to the server, now let's see what it replies back

```
scheme@(lsp-client)> scheme@(lsp-client)> (read-line $3)
$4 = "Content-Length: 121\r"
```

so far, so good

```
scheme@(lsp-client)> (read-line $3)
$5 = "\r"
scheme@(lsp-client)> (read-line $3)
$6 = "{"
scheme@(lsp-client)> (read-line $3)
$7 = "  \"jsonrpc\" : \"2.0\","
scheme@(lsp-client)> (read-line $3)
$8 = "  \"id\" : 1,"
scheme@(lsp-client)> (read-line $3)
$9 = "  \"method\" : \"textDocument/didOpen\""
scheme@(lsp-client)> (read-line $3)
```

at this point I was expecting a closing brace, like this `}`

but instead it hangs, it doesn't even return the prompt back

Note that if I try the same operation at the REPL

```
scheme@(lsp-client)>    (scm->json
          (list
           (cons "jsonrpc" "2.0")
           (cons "id" 1)
           (cons "method" "textDocument/didOpen"))  #:pretty #t )  

{
  "jsonrpc" : "2.0",
  "id" : 1,
  "method" : "textDocument/didOpen"
}scheme@(lsp-client)>
```
it does print the closing brace and the it returns the prompt

Maybe I'm misunderstanding the Fiber use ?

**Comment by aconchillo** [comment]
I know about Fibers but never used it. What happens if you `put-string` directly on the server with the json you want (without using guile-json) ? Does the same thing happen?

**Comment by humanitiesNerd** [comment]
> I know about Fibers but never used it. What happens if you `put-string` directly on the server with the json you want (without using guile-json) ? Does the same thing happen?

yes, the same ting does happen

It happens earlier, actually

```
scheme@(lsp-client)> scheme@(lsp-client)> (read-line $3)
$4 = "Content-Length: 121\r"
scheme@(lsp-client)> (read-line $3)
$5 = "\r"
scheme@(lsp-client)> (read-line $3)
```

it hangs there

So this is related to Fibers, not to guile-json

Thanks

**Comment by aconchillo** [comment]
Closing.
