### ISSUE TITLE
reader syntax for hash tables

### ISSUE THREAD

**Issue by rain-1** [aconchillo/guile-json#25]
```
(define-module (guile-hashtable-reader)
    #:use-module (ice-9 textual-ports)
    #:export ())

(define (read-hashtable _ p)
  (unless (eqv? #\space (read-char p))
    (error 'read-hashtable "must start with #,{,space"))
  (let loop ((h '()))
    (let ((key (read p)))
      (if (equal? (string->symbol "}") key)
	  (let ((h (list 'quasiquote h)))
	    `((@ (ice-9 hash-table) alist->hash-table) ,h))
	  (let ((val (read p)))
	    (when (eof-object? val)
	      (error 'read-hashtable "need an even number of key value pairs for a hashtable"))
	    (loop (cons (cons key (list 'unquote val)) h)))))))

(read-hash-extend #\{ read-hashtable)

;; scheme@(guile-user)> (define x 7)
;; scheme@(guile-user)> (hash-map->list cons #{ 1 (+ 3 5) x x } )
;; $1 = ((x . 7) (1 . 8))

```

Something like this could work maybe, It would be a separate library from guile-json but guile-json could point to it. Any thoughts?

**Comment by aconchillo** [comment]
You beat me to the punch. See last paragraph from:

http://lists.gnu.org/archive/html/guile-user/2018-12/msg00058.html

That would work great actually and would allow keep using hash-tables internally and we would not have any breaking change. Why another library?

**Comment by rain-1** [comment]
A separate library so it can be part of guile scheme in general, anybody who wants to write a literal hash table can use it. If it is too tied in to the json library people might think it's something more than just a notation for hash tables, something related to json/javascript. That was just my opinion but what do you think?

I also thought of a couple improvements. I will quote the keys and give an error if we don't have an even k,v pairing. editing OP with these changes...

**Comment by rain-1** [comment]
I am thinking `#hash(` is a better choice for notation, racket already uses that.

**Comment by aconchillo** [comment]
Probably closed due to this (and related thread):

http://lists.gnu.org/archive/html/guile-user/2018-12/msg00108.html
