### ISSUE TITLE
Change representation of JSON null to symbol null

### ISSUE THREAD

**Issue by johnwcowan** [aconchillo/guile-json#31]
In the current version of `guile-json`, JSON `null` is represented internally as `#nil`.  Because of the magic behavior of `#nil`, this causes certain problems when trying to discriminate between various internal JSON representations.  For example, the programmer will expect `(list? j)` to detect a JSON object and `(null? j)` to detect an empty JSON object.  But these type discriminators are not correct, because they will also return `#t` on `#nil`.  So one must write unidiomatic things like `(or (pair? j) ((eq? j '()))` instead of `(list? j)`.

I suggest (even though it is yet another breaking change) switching to the Scheme symbol `null`.  This is portable, printable and rereadable, and not subject to the above problems.  It is also what Racket and the Chicken `medea` egg (not the `json` egg) use.

**Comment by johnwcowan** [comment]
oops

**Comment by bjoli** [comment]
The racket json library uses a (json-null) parameter for the null value and an optional argument for most procedures that default to (json-null). That seems like a flexible enough way to do it.

**Comment by johnwcowan** [comment]
Too flexible in my opinion.  Settle on one, preferably the symbol null, and
stick with it.

>

**Comment by aconchillo** [comment]
There's a bunch of people using guile-json and making this and #33 would be too much of a breaking change, plus I like supporting symbols when building alists for example.

So, with this in mind, I went for the flexible suggested by @bjoli in #57. I'd love if you could take a look.
