### ISSUE TITLE
JSON numbers must be exact integers or inexact floats

### ISSUE THREAD

**Issue by johnwcowan** [aconchillo/guile-json#32]
JSON numbers have to be, in Scheme terms, either exact integers or inexact reals excluding `+inf.0`, `-inf.0`, and `+nan.0`.  `Guile-json` will blithely output any of these three as well as `1/2`, `3.4+5.6i`, etc., which will not work with other JSON parsers.

**Comment by aconchillo** [comment]
This seems to work for fractions:

```
scheme@(guile-user)> (scm->json 1/7)
0.14285714285714285
scheme@(guile-user)> (scm->json 3/4)
0.75
```

For infinite and complex numbers it works as you mentioned. I'll throw an error if one of those are given.

**Comment by aconchillo** [comment]
Btw, fractions work because guile-json uses `exact->inexact` before writing.

**Comment by christopherlam** [comment]
I was wondering if `Infinity` & `NaN` numbers *have* to be excluded, and the answer is "yes" according to JSON4 http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf (see page 4), but the "proposed" https://json5.org/ seems to allow it. I'd highlight in documentation why/how this decision was made :smile:

**Comment by johnwcowan** [comment]
As the author of XML 1.1, I can assure you that JSON5 is not going to get
traction any time soon.  We need to implement JSON as it is, unimproved and
unchanged.

**Comment by aconchillo** [comment]
Currently, guile-json says it only supports the spec from json.org, so I think we are good. We can worry about json5 in the future. Which, btw, I had no idea it existed.
