### ISSUE TITLE
Symbols are output as JSON strings

### ISSUE THREAD

**Issue by johnwcowan** [aconchillo/guile-json#33]
This will be problematic if anyone depends on it and you decide to switch to the symbol null for JSON null, as I suggested in my previous email.  I think symbols should be invalid as JSON values.

**Comment by aconchillo** [comment]
Might close this issue based on https://github.com/aconchillo/guile-json/issues/31#issuecomment-626292013

**Comment by aconchillo** [comment]
This will still be supproted. See #57 .
