### ISSUE TITLE
Is there a way to work on the software without automake etc?

### ISSUE THREAD

**Issue by rain-1** [aconchillo/guile-json#42]
Is there a way to work on the software without autoreconf, autoconf, automake etc. I had some bugs with it and I was wondering if I could skip debugging and resolving all that. How to run the tests and such with just guile installed?

**Comment by aconchillo** [comment]
Not for guile-json. However, this is probably something it could be asked in guile's mailing list:

https://lists.gnu.org/mailman/listinfo/guile-user
