### ISSUE TITLE
Cannot write the empty object

### ISSUE THREAD

**Issue by civodul** [aconchillo/guile-json#47]
Hello!

In version 3.1.0, `(json-string->scm "{}")` returns the empty list, but `(scm->json-string '())` raises an error.  So it seems we cannot emit the empty object currently, right?

Thanks,
Ludo'.

**Comment by civodul** [comment]
The fix is to change `json-build` so that the condition `(pair? scm)` becomes `(or (pair? scm) (null? scm))`, or simply `(list? scm)` (which is O(N), though).

**Comment by ZelphirKaltstahl** [comment]
I believe this is fixed in https://github.com/aconchillo/guile-json/pull/46/commits/68ade9d55ae637475658546ec80a8cd27d24c728 or https://github.com/aconchillo/guile-json/pull/46 already.

**Comment by aconchillo** [comment]
Hi! Yes, that's fixed in that commit. I will cut a release.

**Comment by aconchillo** [comment]
The fix is now available in version 3.2.0.
