### ISSUE TITLE
Question (Not an issue): Why is a JSON array converted to a Guile vector and not a Guile list?

### ISSUE THREAD

**Issue by pkillnine** [aconchillo/guile-json#59]
This isn't an issue, I'm just curious.

**Comment by aconchillo** [comment]
Hi! Initially guile-json used lists for JSON arrays and hash tables for JSON objects. This was changed in guile-json 3.0.0, see NEWS:

```
  - JSON objects are now defined as alists (instead of hash tables) and JSON
    arrays are now defined as vectors (instead of lists). Both of these
    changes are mainly to use types that have read syntax. This will simplify
    things for the user when defining JSON objects which is probably the most
    common case.
```

Also, see this thread: https://lists.gnu.org/archive/html/guile-user/2018-12/msg00039.html

**Comment by aconchillo** [comment]
Closing. Added a reference to the discussion to the README. Thanks for bringing this up!
