### ISSUE TITLE
Generation of JSON lists could be better

### ISSUE THREAD

**Issue by MazeChaZer** [aconchillo/guile-json#60]
Right now with `(scm->json ... #:pretty #t)`, a list of strings is generated into one line, which leads to very long lines if there are many items in a list. What would you think about adding a line break after each item?

Instead of

```json
[ "foo", "bar", "baz"]
```

it would look like

```json
[
  "foo",
  "bar",
  "baz"
]
```

If you like the idea, I can work on a patch to make this happen.

**Comment by aconchillo** [comment]
That makes sense. Sure, go ahead, thank you!

**Comment by MazeChaZer** [comment]
Cool :)
I will look into this, might take a while.

**Comment by aconchillo** [comment]
> Cool :)
> I will look into this, might take a while.

Awesome. Go for it!

**Comment by lloda** [comment]
Was going to report an issue very much like this, but more precisely about nested lists. I guess any kind of nested structure. If @MazeChaZer can make it work in that case it would be very much appreciated.

**Comment by MazeChaZer** [comment]
I want so solve this in a geral way, so that your issue is also covered. I'm planning to do this for Hacktoberfest, a few weeks from now.

**Comment by aconchillo** [comment]
I believe pretty printing already works for nested objects, so that should be fine. The only one that doesn't work is lists. If i'm not wrong this will be adding 1 line of code and changing 2 (for opening/closing brackets). And it will be generic for nested structures inside the list itself.

**Comment by aconchillo** [comment]
I have added the `hacktoberfest` topic to the project so anyone can participate.
