### ISSUE TITLE
json->scm reverses order of keys in object

### ISSUE THREAD

**Issue by arunisaac** [aconchillo/guile-json#77]
json->scm reverses the order of keys in an object. For example, json-scm converts `{"spam": 1, "ham": 2, "eggs": 3}` to `(("eggs" . 3) ("ham" . 2) ("spam" . 1))`. Now, I get that the order of keys is supposed to be insignificant. Nevertheless, it would be nice if the order were preserved.

My specific use case is that I am working on a [GraphQL](https://graphql.org/) implementation for Guile, and having json->scm reverse the keys feels weird.

Thank you and happy new year!

**Comment by aconchillo** [comment]
Hi @arunisaac . This is now supported in guile-json 4.7.0. You will need to use a new keyword argument `#:ordered` to keep object ordering. I hope that works!

Very excited to get GraphQL support!

**Comment by aconchillo** [comment]
Btw, happy new year as well!

**Comment by arunisaac** [comment]
> This is now supported in guile-json 4.7.0. You will need to use a new
> keyword argument `#:ordered` to keep object ordering. I hope that
> works!

Thanks for the quick response! I checked and it works. This could be
even better if done transparently without the new #:ordered keyword
argument. Internal implementation details such as ordering should not be
exposed to the user. What do you think?

> Very excited to get GraphQL support!

Thanks! It is at a very early stage with hardly any documentation. But,
you can see early progress at https://kolam.systemreboot.net/

**Comment by aconchillo** [comment]
> Thanks for the quick response! I checked and it works. This could be even better if done transparently without the new #:ordered keyword argument. Internal implementation details such as ordering should not be exposed to the user. What do you think?

I thought about it, but it would break the previous default behavior and I didn't want to do that. So my thought was: by default you don't care about ordering or whatever guile-json returns, if you want an explicit ordered return (because you care about ordering) then you need to specify it.

> Thanks! It is at a very early stage with hardly any documentation. But, you can see early progress at https://kolam.systemreboot.net/

I'll take a look, thanks!

**Comment by arunisaac** [comment]
> I thought about it, but it would break the previous default behavior
> and I didn't want to do that. So my thought was: by default you don't
> care about ordering or whatever guile-json returns, if you want an
> explicit ordered return (because you care about ordering) then you
> need to specify it.

Sounds good. This works too!
