### ISSUE TITLE
How can I mutate the value?

### ISSUE THREAD

**Issue by NalaGinrut** [aconchillo/guile-json#81]
For example, here's a s-expr parsed from a json:

```
(("aaa" . 1) ("bbb" . 2))
```

Now I want to modify the value of "aaa" and send to a certain API. The problem is that the quoted list in Guile is always immutable, so I can't change the value of "aaa" with `assoc-set!`. 

Of course, I can construct a new alist for this simple case. But my actual case is a complex and nested json structure, so reconstructing it with new values becomes hard.

Is there any idea about such a situation?

**Comment by NalaGinrut** [comment]
@aconchillo sorry, I updated the description.

**Comment by NalaGinrut** [comment]
@ZelphirKaltstahl Nice! Thank you very much! I'll shamelessly add it to my utils module. ;-)

**Comment by NalaGinrut** [comment]
@ZelphirKaltstahl BTW, did you generate this code with copilot? I tried the same prompt and get the same result. ;-D

**Comment by ZelphirKaltstahl** [comment]
@NalaGinrut You are welcome. No, it was generated by me thinking about it for a while. I already have a small library of alist functions in my Guile examples repo over at notabug, but there was no function for functionally setting an entry. Maybe Copilot has been reading this issue? In that case I should probably not post code in issues any longer. Or on Github. Hm.

How much was the Copilot generated code the same? Same variable names? Same way of constructing the exception? Or were there slight differences?

**Comment by aconchillo** [comment]
@NalaGinrut OK to close the issue?

**Comment by NalaGinrut** [comment]
@aconchillo please feel free to close it. 
@ZelphirKaltstahl It's thoroughly copied, I guess copilot keeps uploading my code and learning. Fortunately, my code is libre so I don't care. But, you may imagine...;-)
